import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";

const webRoot = path.resolve(__dirname, "../../web");

test("frontend chat page keeps runtime details in settings without secrets", async () => {
  const [html, app, css] = await Promise.all([
    readFile(path.join(webRoot, "index.html"), "utf8"),
    readFile(path.join(webRoot, "app.js"), "utf8"),
    readFile(path.join(webRoot, "styles.css"), "utf8"),
  ]);

  assert.match(html, /living-room-design/);
  assert.match(html, /viewport-fit=cover/);
  assert.match(html, /8 agents ready/);
  assert.match(html, /roomSubtitle/);
  assert.match(html, /settingsPanel/);
  assert.match(html, /role="dialog"/);
  assert.match(html, /aria-modal="true"/);
  assert.match(html, /id="roomRail"/);
  assert.match(html, /id="chatShell"/);
  assert.match(html, /tabindex="-1"/);
  assert.match(html, /id="topicBar"/);
  assert.match(html, /id="livingOverview"/);
  assert.match(html, /class="living-overview collapsed"/);
  assert.match(html, /id="overviewToggle"/);
  assert.match(html, /aria-expanded="false"/);
  assert.match(html, /aria-controls="overviewPanel"/);
  assert.match(html, /id="overviewToggleSummary"/);
  assert.match(html, /id="overviewPanel"/);
  assert.match(html, /hidden/);
  assert.match(html, /id="evidenceStrip"/);
  assert.match(html, /Context visibility and room rhythm evidence/);
  assert.match(html, /id="timelinePreview"/);
  assert.match(html, /id="archivePreview"/);
  assert.match(html, /id="memoryContestPreview"/);
  assert.match(html, /<span>Memory Pressure<\/span>/);
  assert.match(html, /id="agentContinuityPreview"/);
  assert.match(html, /id="providerBoundaryPreview"/);
  assert.match(html, /Long-Run Readiness/);
  assert.match(html, /id="longRunReadinessCount"/);
  assert.match(html, /id="longRunReadinessPreview"/);
  assert.match(html, /messageList/);
  assert.match(html, /newMessageJump/);
  assert.match(html, /mentionButton/);
  assert.match(html, /mentionPopover/);
  assert.match(html, /mentionTray/);
  assert.match(html, /addContextButton/);
  assert.match(html, /contextTray/);
  assert.match(html, /contextAuditList/);
  assert.match(html, /Context Audit/);
  assert.match(html, /openQuestionList/);
  assert.match(html, /Open Questions/);
  assert.match(html, /memoryPressureList/);
  assert.match(html, /Memory Pressure/);
  assert.match(html, /personaEvolutionList/);
  assert.match(html, /Agent Evolution/);
  assert.match(html, /workspaceList/);
  assert.match(html, /Private Workspaces/);
  assert.match(html, /yoloSpaceList/);
  assert.match(html, /YOLO Spaces/);
  assert.match(html, /skillCapsuleList/);
  assert.match(html, /Skill Capsules/);
  assert.match(html, /capabilityHintList/);
  assert.match(html, /Capability Hints/);
  assert.match(html, /sideEffectList/);
  assert.match(html, /Action Requests/);
  assert.match(html, /topicProposalList/);
  assert.match(html, /Topic Proposals/);
  assert.match(html, /mixedReviewList/);
  assert.match(html, /Mixed Review Pressure/);
  assert.match(html, /invitationList/);
  assert.match(html, /Invitations/);
  assert.match(html, /silenceList/);
  assert.match(html, /Silences/);
  assert.match(html, /pressureBoundaryList/);
  assert.match(html, /Pressure Boundaries/);
  assert.match(html, /roomRhythmList/);
  assert.match(html, /Room Rhythm/);
  assert.match(html, /autonomyTickButton/);
  assert.match(html, /autonomyState/);
  assert.match(html, /reopen after silence/);
  assert.match(html, /providerBoundaryList/);
  assert.match(html, /Provider Boundaries/);
  assert.match(html, /archiveNowButton/);
  assert.match(html, /archiveReviewButton/);
  assert.match(html, /archiveRhythmButton/);
  assert.match(html, /archiveApplyRepairButton/);
  assert.match(html, /archiveReviewList/);
  assert.match(html, /archiveState/);
  assert.match(html, /Archive Today/);
  assert.match(html, /Ask Review/);
  assert.match(html, /Daily Rhythm/);
  assert.match(html, /Apply Accepted Repair/);
  assert.match(html, /Archives compress room time/);
  assert.match(html, /composer-tools/);
  assert.match(html, /id="formatButton"/);
  assert.match(html, /Enter 发送/);
  assert.match(html, /id="expandComposerButton"/);
  assert.doesNotMatch(html, /message-pager/);
  assert.match(app, /kimi_member_01/);
  assert.match(app, /kimi_member_02/);
  assert.match(app, /mimo_member_01/);
  assert.match(app, /mimo_member_02/);
  assert.match(app, /mimo_member_03/);
  assert.match(app, /mimo_member_04/);
  assert.doesNotMatch(app, /agentAvatarSources/);
  assert.doesNotMatch(app, /\.\/assets\/avatars\//);
  assert.match(app, /agentAvatarMarkup\(message\.author, message\.initials\)/);
  assert.match(app, /agentAvatarMarkup\(agent\.id, agent\.initials\)/);
  assert.match(app, /data-agent-id=/);
  assert.match(app, /fetchJson\("\/api\/room\/state"/);
  assert.match(app, /fetchJson\("\/api\/room\/messages"/);
  assert.match(app, /fetchJson\("\/api\/room\/archive\/daily"/);
  assert.match(app, /fetchJson\("\/api\/room\/archive\/repairs\/apply"/);
  assert.match(app, /fetchJson\("\/api\/room\/autonomy\/tick"/);
  assert.match(app, /fetchJson\("\/api\/room\/side-effects\/approve"/);
  assert.match(app, /fetchJson\("\/api\/room\/side-effects\/execute"/);
  assert.match(app, /fetchJson\("\/api\/room\/side-effects\/expire"/);
  assert.match(app, /sideEffectReviews/);
  assert.match(app, /sideEffectReviewsFor/);
  assert.match(app, /Ask review for side-effect request/);
  assert.match(app, /请审阅这条外部副作用请求/);
  assert.match(app, /mixedReviewPressures/);
  assert.match(app, /mixed review pressure/);
  assert.match(app, /responseKindSummary/);
  assert.match(app, /xhrJson/);
  assert.match(app, /XMLHttpRequest/);
  assert.match(app, /applyRequestHeaders/);
  assert.match(app, /内部房间记录/);
  assert.match(app, /renderTopics/);
  assert.match(app, /data-topic-context-ref/);
  assert.match(app, /topicRevivalCount/);
  assert.match(app, /topicOpenQuestionCount/);
  assert.match(app, /topic-revival/);
  assert.match(app, /topic-question/);
  assert.match(app, /topicContextRef/);
  assert.match(app, /activeTopicId/);
  assert.match(app, /sendCurrentMessage/);
  assert.match(app, /createDailyArchiveFromRoom/);
  assert.match(app, /requestLatestArchiveReview/);
  assert.match(app, /requestDailyRhythmCheckIn/);
  assert.match(app, /dailyRhythmPrompt/);
  assert.match(app, /dailyRhythmContextRefs/);
  assert.match(app, /dailyRhythmOpenQuestionRefs/);
  assert.match(app, /dailyRhythmMemoryRefs/);
  assert.match(app, /dailyRhythmProtocolRefs/);
  assert.match(app, /dailyRhythmPersonaRefs/);
  assert.match(app, /uniqueRoomRefs/);
  assert.match(app, /applyLatestAcceptedArchiveRepair/);
  assert.match(app, /requestAutonomyTickFromRoom/);
  assert.match(app, /roomRhythmActionLabel/);
  assert.match(app, /memory hygiene/);
  assert.match(app, /continuity review/);
  assert.match(app, /provider boundary review/);
  assert.match(app, /open question revisit/);
  assert.match(app, /invitation review/);
  assert.match(app, /handoff review/);
  assert.match(app, /autonomyTicks/);
  assert.match(app, /silence re-entry/);
  assert.match(app, /renderMemoryClaimList/);
  assert.match(app, /memoryStateBoundaryLabel/);
  assert.match(app, /memorySourceRefsMarkup/);
  assert.match(app, /requestProtocolReview/);
  assert.match(app, /protocolReviewPrompt/);
  assert.match(app, /requestTopicProposalReview/);
  assert.match(app, /topicProposalReviewPrompt/);
  assert.match(app, /renderProtocolList/);
  assert.match(app, /protocolLifetimeLabel/);
  assert.match(app, /requestHandoffReview/);
  assert.match(app, /handoffReviewPrompt/);
  assert.match(app, /renderHandoffList/);
  assert.match(app, /handoffBoundaryLabel/);
  assert.match(app, /handoffResponsesMarkup/);
  assert.match(app, /latestHandoffResponseLabel/);
  assert.match(app, /renderArchiveList/);
  assert.match(app, /archiveStatMarkup/);
  assert.match(app, /archiveRevisionMarkup/);
  assert.match(app, /expireSideEffectPermission/);
  assert.match(app, /approveSideEffectPermission/);
  assert.match(app, /executeSideEffectPermission/);
  assert.match(app, /findSideEffect/);
  assert.match(app, /sideEffectMatchesRef/);
  assert.match(app, /data-side-effect-approve-ref/);
  assert.match(app, /data-side-effect-execute-ref/);
  assert.match(app, /data-side-effect-expire-ref/);
  assert.match(app, /data-side-effect-review-ref/);
  assert.match(app, /Unused approved side-effect permission/);
  assert.match(app, /未执行外部动作/);
  assert.match(app, /latestAcceptedUnappliedArchiveRepair/);
  assert.match(app, /latestArchive/);
  assert.match(app, /archiveTimezone/);
  assert.match(app, /archiveDate/);
  assert.match(app, /archiveReviews/);
  assert.match(app, /archive review/);
  assert.match(app, /dailyArchiveReviewPrompt/);
  assert.match(app, /请审阅这份 daily time skeleton/);
  assert.doesNotMatch(app, /请审阅 daily archive/);
  assert.match(app, /daily rhythm invitation/);
  assert.match(app, /not a command to speak, consensus request, or archive mutation/);
  assert.match(app, /repair review/);
  assert.match(app, /这是时间骨架，不是共识/);
  assert.match(app, /contextRefs:\s*\[archive\.archiveId\]/);
  assert.match(app, /agent 可反驳、补充或沉默/);
  assert.match(app, /daily rhythm check-in/);
  assert.match(app, /不会自动创建 archive/);
  assert.match(app, /先看 refs 再决定是否接话/);
  assert.match(app, /slice\(0,\s*10\)/);
  assert.match(app, /不要把这当成任务分派或共识生成/);
  assert.match(app, /No archive reviews yet/);
  assert.match(app, /daily archive 会打开审阅节律/);
  assert.match(app, /原 archive 保持不变/);
  assert.match(app, /appendPendingUserMessage/);
  assert.match(app, /selectedContextRefs/);
  assert.match(app, /context-selected/);
  assert.match(app, /body: JSON\.stringify\(\{[\s\S]*contextRefs,/);
  assert.match(app, /renderContextTray/);
  assert.match(app, /messageContextRefsMarkup/);
  assert.match(app, /replyToMessage/);
  assert.match(app, /data-message-action="more"/);
  assert.match(app, /data-message-more-ref/);
  assert.match(app, /messageActionMenuMarkup/);
  assert.match(app, /data-message-menu-action="context"/);
  assert.match(app, /data-message-menu-action="reply"/);
  assert.match(app, /data-message-menu-action="copy-ref"/);
  assert.match(app, /data-message-menu-action="copy-text"/);
  assert.match(app, /copyTextToClipboard/);
  assert.match(app, /event\.stopPropagation\(\)/);
  assert.match(app, /clipboard unavailable/);
  assert.match(app, /openMessageActionRef/);
  assert.match(app, /composerDraftMode/);
  assert.match(app, /composerExpanded/);
  assert.match(app, /composerTextareaMaxHeight/);
  assert.match(app, /effectiveViewportHeight/);
  assert.match(app, /visualViewport/);
  assert.match(app, /formatButton\.addEventListener/);
  assert.match(app, /expandComposerButton\.addEventListener/);
  assert.match(app, /data-social-context-ref/);
  assert.match(app, /social-context-button/);
  assert.match(app, /contextRefDescriptor/);
  assert.match(app, /topic proposal/);
  assert.match(app, /findById/);
  assert.match(app, /data-memory-claim-review-ref/);
  assert.match(app, /data-social-context-ref="\$\{escapeHtml\(claim\.memoryId\)\}"/);
  assert.match(app, /data-handoff-review-ref/);
  assert.match(app, /data-social-context-ref="\$\{escapeHtml\(handoff\.handoffId\)\}"/);
  assert.match(app, /data-protocol-review-ref/);
  assert.match(app, /data-topic-proposal-review-ref/);
  assert.match(app, /data-social-context-ref="\$\{escapeHtml\(protocol\.protocolId\)\}"/);
  assert.match(app, /data-social-context-ref="\$\{escapeHtml\(archive\.archiveId\)\}"/);
  assert.match(app, /latestVisibleMessageRef/);
  assert.match(app, /room\.messages = chatStreamMessages\(state\.messages\)/);
  assert.match(app, /function isChatStreamMessage/);
  assert.match(app, /shortRef/);
  assert.match(app, /scheduleRoomPolling/);
  assert.match(app, /ROOM_STATE_POLL_INTERVAL_MS\s*=\s*3_000/);
  assert.match(app, /startRoomPolling\(\)/);
  assert.match(app, /skipUnchanged/);
  assert.match(app, /visibilitychange/);
  assert.match(app, /preserveComposerState/);
  assert.match(app, /消息已发出/);
  assert.match(app, /describeWakeTargets/);
  assert.match(app, /正在唤醒所有 agent/);
  assert.match(app, /selectedMentions/);
  assert.match(app, /openMentionPopover/);
  assert.match(app, /handleMentionKeydown/);
  assert.match(app, /setMentionActiveIndex/);
  assert.match(app, /aria-activedescendant/);
  assert.match(app, /aria-selected/);
  assert.match(app, /insertMention/);
  assert.match(app, /extractKnownMentions/);
  assert.match(app, /mentions,\s*\n\s*contextRefs,/);
  assert.match(app, /messageMentionsMarkup/);
  assert.match(app, /contextAudits/);
  assert.match(app, /longRunOperationalSummary/);
  assert.match(app, /autonomyScheduler/);
  assert.match(app, /timeline:\s*\[\]/);
  assert.match(app, /state\.timeline/);
  assert.match(app, /renderLivingOverview/);
  assert.match(app, /livingOverviewExpanded/);
  assert.match(app, /overviewToggle\.addEventListener/);
  assert.match(app, /syncLivingOverviewDisclosure/);
  assert.match(app, /overviewPanel\.hidden = !livingOverviewExpanded/);
  assert.match(app, /renderEvidenceStrip/);
  assert.match(app, /contextVisibilitySummary/);
  assert.match(app, /roomRhythmEvidenceSummary/);
  assert.match(app, /roomRhythmDecisionRefs/);
  assert.match(app, /roomRhythmDecisionDetail/);
  assert.match(app, /roomRhythmChoiceSetMarkup/);
  assert.match(app, /roomRhythmChoiceEvidenceLabel/);
  assert.match(app, /roomRhythmChoiceCountLabel/);
  assert.match(app, /roomRhythmRefsMarkup/);
  assert.match(app, /missing ledger evidence/);
  assert.match(app, /missing target refs/);
  assert.match(app, /roomRhythmActionLabel\(tick\.action\)/);
  assert.match(app, /findAutonomyTick/);
  assert.match(app, /type: "room rhythm"/);
  assert.match(app, /className: "rhythm-context"/);
  assert.match(app, /data-room-rhythm-ref/);
  assert.match(app, /data-room-rhythm-choice-ref/);
  assert.match(app, /Add room rhythm decision ref/);
  assert.match(app, /longTermRhythmEvidenceSummary/);
  assert.match(app, /longTermRhythmEvidenceRefs/);
  assert.match(app, /longTermRhythmTickRefs/);
  assert.match(app, /longTermRhythmRefsMarkup/);
  assert.match(app, /data-long-rhythm-ref/);
  assert.match(app, /autonomyRhythmBalanceSummary/);
  assert.match(app, /AUTONOMY_RHYTHM_BALANCE_MONOPOLY_THRESHOLD/);
  assert.match(app, /rhythm-balance-evidence/);
  assert.match(app, /data-rhythm-balance-ref/);
  assert.match(app, /schedulerEvidenceSummary/);
  assert.match(app, /schedulerCadenceSummary/);
  assert.match(app, /scheduler_continuity/);
  assert.match(app, /continuityReviewAfterMs/);
  assert.match(app, /memoryHygieneReviewAfterMs/);
  assert.match(app, /providerBoundaryOverviewSummary/);
  assert.match(app, /providerBoundaryPreviewCandidate/);
  assert.match(app, /providerBoundaryOverviewPressureSummary/);
  assert.match(app, /providerBoundaryOverviewPressureMarkup/);
  assert.match(app, /providerBoundaryOverviewFactMarkup/);
  assert.match(app, /providerBoundaryOverviewRefsMarkup/);
  assert.match(app, /boundary pressure/);
  assert.match(app, /provider boundary pressure ref/);
  assert.match(app, /providerBoundaryEvidenceRefs/);
  assert.match(app, /findProviderBoundaryByEvidenceRef/);
  assert.match(app, /providerBoundaryContextDescriptor/);
  assert.match(app, /providerBoundaryChoicePressureSummary/);
  assert.match(app, /providerBoundaryChoicePressureRefs/);
  assert.match(app, /providerBoundaryCount\.textContent = providerOverview\.countLabel/);
  assert.match(app, /longRunReadinessSummary/);
  assert.match(app, /renderLongRunReadinessPreview/);
  assert.match(app, /longRunReadinessDomainMarkup/);
  assert.match(app, /longRunRunBalanceSummary/);
  assert.match(app, /longRunRunBalanceMarkup/);
  assert.match(app, /longRunRunBalanceFactMarkup/);
  assert.match(app, /long-run-run-balance/);
  assert.match(app, /longRunGuardrailsSummary/);
  assert.match(app, /longRunGuardrailsMarkup/);
  assert.match(app, /longRunGuardrailFactMarkup/);
  assert.match(app, /long-run-guardrails/);
  assert.match(app, /activeSpeakers/);
  assert.match(app, /minimumActiveSpeakers/);
  assert.match(app, /speakerBalanceGaps/);
  assert.match(app, /deferredSpeeches/);
  assert.match(app, /deferredRecoveryContextRefs/);
  assert.match(app, /deferredRecoveryGaps/);
  assert.match(app, /longRunActionBoundarySummary/);
  assert.match(app, /longRunActionBoundaryMarkup/);
  assert.match(app, /longRunActionFactMarkup/);
  assert.match(app, /long-run-action-boundary/);
  assert.match(app, /action_boundary/);
  assert.match(app, /unapprovedResults/);
  assert.match(app, /actionBoundaryGaps/);
  assert.match(app, /longRunSchedulerContinuitySummary/);
  assert.match(app, /longRunSchedulerContinuityMarkup/);
  assert.match(app, /longRunSchedulerFactMarkup/);
  assert.match(app, /long-run-scheduler-continuity/);
  assert.match(app, /longRunLongTermRhythmSummary/);
  assert.match(app, /longRunLongTermRhythmMarkup/);
  assert.match(app, /longRunLongRhythmFactMarkup/);
  assert.match(app, /long-run-long-rhythm/);
  assert.match(app, /idleSocialActions/);
  assert.match(app, /idleSocialTargets/);
  assert.match(app, /idleSocialEvidenceRefs/);
  assert.match(app, /choiceSetTargetRefs/);
  assert.match(app, /choiceSetEvidenceRefs/);
  assert.match(app, /choiceSetGaps/);
  assert.match(app, /longRunSilenceReentrySummary/);
  assert.match(app, /longRunSilenceReentryMarkup/);
  assert.match(app, /longRunSilenceFactMarkup/);
  assert.match(app, /long-run-silence-reentry/);
  assert.match(app, /silence_reentry/);
  assert.match(app, /configuredSilenceReentryMs/);
  assert.match(app, /quietAnchorRefs/);
  assert.match(app, /preservedSilenceAnchorRefs/);
  assert.match(app, /missingPreservedSilenceActions/);
  assert.match(app, /silenceReentryGaps/);
  assert.match(app, /longRunArchiveRhythmSummary/);
  assert.match(app, /longRunArchiveRhythmMarkup/);
  assert.match(app, /longRunArchiveRhythmFactMarkup/);
  assert.match(app, /long-run-archive-rhythm/);
  assert.match(app, /archiveReviewLedgerEvents/);
  assert.match(app, /archiveEvidenceGaps/);
  assert.match(app, /acceptedMemoryArchives/);
  assert.match(app, /acceptedMemoryArchiveEvidenceRefs/);
  assert.match(app, /acceptedMemoryArchivesWithoutEvidence/);
  assert.match(app, /longRunMemoryContestSummary/);
  assert.match(app, /longRunMemoryContestMarkup/);
  assert.match(app, /longRunMemoryContestFactMarkup/);
  assert.match(app, /long-run-memory-contest/);
  assert.match(app, /memoryHygieneTargets/);
  assert.match(app, /acceptedMemoryArchives/);
  assert.match(app, /acceptedMemoryArchiveEvidenceRefs/);
  assert.match(app, /acceptedMemoryArchivesWithoutEvidence/);
  assert.match(app, /contestEvidenceGaps/);
  assert.match(app, /longRunAgentContinuitySummary/);
  assert.match(app, /longRunAgentContinuityMarkup/);
  assert.match(app, /longRunAgentContinuityFactMarkup/);
  assert.match(app, /long-run-agent-continuity/);
  assert.match(app, /acceptedPersonaDeltas/);
  assert.match(app, /acceptedArchivedContinuityItems/);
  assert.match(app, /archiveContinuityEvidenceRefs/);
  assert.match(app, /longRunSocialLoopEvidenceSummary/);
  assert.match(app, /longRunSocialLoopEvidenceMarkup/);
  assert.match(app, /longRunSocialFactMarkup/);
  assert.match(app, /long-run-social-loop/);
  assert.match(app, /choicesAfterUserSilence/);
  assert.match(app, /interruptedChoices/);
  assert.match(app, /requiredChoiceKinds/);
  assert.match(app, /coveredChoiceKinds/);
  assert.match(app, /missingChoiceKinds/);
  assert.match(app, /choiceCoverageGaps/);
  assert.match(app, /requiredRoomEventPressureKinds/);
  assert.match(app, /coveredRoomEventPressureKinds/);
  assert.match(app, /missingRoomEventPressureKinds/);
  assert.match(app, /roomEventPressureCoverageGaps/);
  assert.match(app, /roomEventPressureRefs/);
  assert.match(app, /archivePressureChoices/);
  assert.match(app, /providerBoundaryPressureChoices/);
  assert.match(app, /silenceReentryPressureChoices/);
  assert.match(app, /idleSocialPressureChoices/);
  assert.match(app, /choiceSilenceWindows/);
  assert.match(app, /cleanChoiceSilenceWindows/);
  assert.match(app, /interruptedSilenceWindows/);
  assert.match(app, /interruptingUserMessages/);
  assert.match(app, /lineageGaps/);
  assert.match(app, /longRunProviderBoundarySummary/);
  assert.match(app, /longRunProviderBoundaryMarkup/);
  assert.match(app, /longRunProviderFactMarkup/);
  assert.match(app, /long-run-provider-boundary/);
  assert.match(app, /secretLikeDiagnostics/);
  assert.match(app, /requiredChoicePressureKinds/);
  assert.match(app, /coveredChoicePressureKinds/);
  assert.match(app, /missingChoicePressureKinds/);
  assert.match(app, /choicePressureCoverageGaps/);
  assert.match(app, /repairPressureRefs/);
  assert.match(app, /retryPressureRefs/);
  assert.match(app, /contestedMemoryPressureRefs/);
  assert.match(app, /longRunSedimentEvidenceSummary/);
  assert.match(app, /longRunSedimentEvidenceMarkup/);
  assert.match(app, /longRunSedimentFactMarkup/);
  assert.match(app, /long-run-sediment-evidence/);
  assert.match(app, /personaLikeMemory/);
  assert.match(app, /acceptedWithoutReview/);
  assert.match(app, /memoryReviewTraces/);
  assert.match(app, /roleClaims/);
  assert.match(app, /dailyMoodRecords/);
  assert.match(app, /continuityEvidenceRefs/);
  assert.match(app, /continuityEvidenceGaps/);
  assert.match(app, /longRunContextVisibilitySummary/);
  assert.match(app, /longRunContextVisibilityMarkup/);
  assert.match(app, /longRunContextFactMarkup/);
  assert.match(app, /long-run-context-visibility/);
  assert.match(app, /coVisibleDomains/);
  assert.match(app, /criticalFragmentGaps/);
  assert.match(app, /longRunReadinessRefsMarkup/);
  assert.match(app, /longRunFreshnessLabel/);
  assert.match(app, /stale long-run report/);
  assert.match(app, /Add long-run rhythm balance ref/);
  assert.match(app, /Add long-run guardrail ref/);
  assert.match(app, /Add action boundary ref/);
  assert.match(app, /Add scheduler continuity ref/);
  assert.match(app, /Add long-term rhythm ref/);
  assert.match(app, /Add silence re-entry ref/);
  assert.match(app, /Add archive rhythm ref/);
  assert.match(app, /Add memory contest ref/);
  assert.match(app, /Add agent continuity ref/);
  assert.match(app, /Add social loop evidence ref/);
  assert.match(app, /Add long-run provider boundary ref/);
  assert.match(app, /Add sediment evidence ref/);
  assert.match(app, /Add context visibility ref/);
  assert.match(app, /data-long-run-readiness-ref/);
  assert.match(app, /long-run report/);
  assert.match(app, /evidencePillMarkup/);
  assert.match(app, /overviewEvidenceRefs/);
  assert.match(app, /firstArchiveEvidenceRef/);
  assert.match(app, /archivePreviewCandidate/);
  assert.match(app, /archiveEvidenceRefs/);
  assert.match(app, /archiveReviewRefsForArchive/);
  assert.match(app, /archiveReviewsForArchive/);
  assert.match(app, /archiveRhythmSummary/);
  assert.match(app, /archiveRhythmSummaryMarkup/);
  assert.match(app, /archiveRhythmFactMarkup/);
  assert.match(app, /archiveRhythmRefsMarkup/);
  assert.match(app, /time rhythm/);
  assert.match(app, /archive rhythm ref/);
  assert.match(app, /firstMemoryContestRef/);
  assert.match(app, /memoryContestPreviewCandidate/);
  assert.match(app, /memoryClaimEvidenceRefs/);
  assert.match(app, /memoryHygienePressureSummary/);
  assert.match(app, /memoryHygieneSummaryMarkup/);
  assert.match(app, /memoryHygieneFactMarkup/);
  assert.match(app, /memoryHygieneRefsMarkup/);
  assert.match(app, /sourcePressureRefs: uniqueRoomRefs/);
  assert.match(app, /hygiene pressure/);
  assert.match(app, /findMemoryClaimByEvidenceRef/);
  assert.match(app, /memoryContextDescriptor/);
  assert.match(app, /evidencePillMarkup\("co-visible", visibility\.coVisible\)/);
  assert.match(app, /coVisibleContextAuditSummary/);
  assert.match(app, /coVisibleSummaryRefs/);
  assert.match(app, /\.\.\.\(visibility\.coVisibleRefs \?\? \[\]\)/);
  assert.match(app, /selectedByType\?\.persona_delta/);
  assert.match(app, /selectedByType\?\.persona_projection/);
  assert.match(app, /evidencePillMarkup\("continuity"/);
  assert.match(app, /archiveContinuityVisibleInContext/);
  assert.match(app, /contextArchiveRefs/);
  assert.match(app, /fragment\.type === "daily_archive_ref"/);
  assert.match(app, /archiveContinuityRows\(archive\)/);
  assert.match(app, /dailyRhythmProviderBoundaryRefs/);
  assert.match(app, /selectedByType\?\.provider_boundary/);
  assert.match(app, /selectedByType\?\.daily_archive_ref/);
  assert.match(app, /type\.startsWith\("memory_"\)/);
  assert.match(app, /evidencePillMarkup\("social"/);
  assert.match(app, /isSocialLineageContextFragment/);
  assert.match(app, /contextSocialLineageRefs/);
  assert.match(app, /firstContextSocialLineageRef/);
  assert.match(app, /type === "mixed_review_pressure"/);
  assert.match(app, /type === "open_question"/);
  assert.match(app, /type === "handoff_packet"/);
  assert.match(app, /type === "invitation_packet"/);
  assert.match(app, /type === "skill_capsule_ref"/);
  assert.match(app, /type === "capability_ref"/);
  assert.match(app, /topic_proposal_/);
  assert.match(app, /Room rhythm/);
  assert.match(app, /Long rhythm/);
  assert.match(app, /evidencePillMarkup\("review"/);
  assert.match(app, /evidencePillMarkup\("memory hygiene"/);
  assert.match(app, /evidencePillMarkup\("continuity"/);
  assert.match(app, /evidencePillMarkup\("silence"/);
  assert.match(app, /evidencePillMarkup\("questions"/);
  assert.match(app, /evidencePillMarkup\("handoffs"/);
  assert.match(app, /evidencePillMarkup\("invites"/);
  assert.match(app, /memoryReviews\.length > 0/);
  assert.match(app, /personaDeltaReviews\.length > 0/);
  assert.match(app, /archiveReviews\.length > 0/);
  assert.match(app, /openQuestions\.length > 0/);
  assert.match(app, /handoffReviews\.length > 0/);
  assert.match(app, /invitationReviews\.length > 0/);
  assert.match(app, /tick\.action === "silence_reentry"/);
  assert.match(app, /tick\.action === "open_question_revisit"/);
  assert.match(app, /tick\.action === "handoff_review"/);
  assert.match(app, /tick\.action === "invitation_review"/);
  assert.match(app, /archiveRefs\.slice\(0, 2\)/);
  assert.match(app, /questionRefs\.slice\(0, 1\)/);
  assert.match(app, /handoffRefs\.slice\(0, 1\)/);
  assert.match(app, /invitationRefs\.slice\(0, 1\)/);
  assert.match(app, /tick\.anchorEventId/);
  assert.match(app, /Scheduler/);
  assert.match(app, /schedulerChoiceEvidenceSummary/);
  assert.match(app, /completedTickCount/);
  assert.match(app, /skippedOverlapCount/);
  assert.match(app, /overdueTickCount/);
  assert.match(app, /overrunTickCount/);
  assert.match(app, /nextTickDueAt/);
  assert.match(app, /lastExpectedTickDueAt/);
  assert.match(app, /lastScheduleDriftMs/);
  assert.match(app, /lastDurationMs/);
  assert.match(app, /lastOverrunByMs/);
  assert.match(app, /schedulerNextDueLabel/);
  assert.match(app, /schedulerContinuitySummary/);
  assert.match(app, /durationMsCompactLabel/);
  assert.match(app, /schedulerLedgerRefs/);
  assert.match(app, /schedulerRefsMarkup/);
  assert.match(app, /lastTargetRefs/);
  assert.match(app, /lastChoiceSetRefs/);
  assert.match(app, /lastChoiceSetOptionCount/);
  assert.match(app, /lastChoiceSetTargetRefs/);
  assert.match(app, /lastChoiceSetEvidenceRefs/);
  assert.match(app, /lastChoiceSetOptionsWithoutEvidenceRefs/);
  assert.match(app, /lastChoiceSetTargetedOptionsWithoutTargetRefs/);
  assert.match(app, /evidence gaps/);
  assert.match(app, /tick\.targetRefs/);
  assert.match(app, /autonomyChoiceSetRefs/);
  assert.match(app, /tick\?\.choiceSet/);
  assert.match(app, /data-scheduler-rhythm-ref/);
  assert.match(app, /Next room rhythm/);
  assert.match(app, /Last refs/);
  assert.match(app, /Scheduler is disabled; manual autonomy tick remains available/);
  assert.match(app, /Carry refs/);
  assert.match(app, /renderTimelinePreview/);
  assert.match(app, /timelineEvidenceSummary/);
  assert.match(app, /timelineEvidenceSummaryMarkup/);
  assert.match(app, /timelineEvidenceFactMarkup/);
  assert.match(app, /timelineEvidenceRefsMarkup/);
  assert.match(app, /ledger timeline/);
  assert.match(app, /timeline evidence ref/);
  assert.match(app, /agentContinuityPreviewCandidate/);
  assert.match(app, /agentContinuitySedimentSummary/);
  assert.match(app, /agentContinuitySummaryMarkup/);
  assert.match(app, /agentContinuityFactMarkup/);
  assert.match(app, /agentContinuitySummaryRefsMarkup/);
  assert.match(app, /continuity sediment/);
  assert.match(app, /response refs/);
  assert.match(app, /evidenceCount/);
  assert.match(app, /memoryContestClaims/);
  assert.match(app, /agentContinuityCountValue/);
  assert.match(app, /timelineCategoryLabel/);
  assert.match(app, /data-social-context-ref="\$\{escapeHtml\(ref\)\}"/);
  assert.match(app, /auditFactMarkup/);
  assert.match(app, /auditFragmentGroupMarkup/);
  assert.match(app, /auditFragmentPressureLineageMarkup/);
  assert.match(app, /auditFragmentPressureRefs/);
  assert.match(app, /auditCoVisibleMarkup/);
  assert.match(app, /auditCoVisibleSummary/);
  assert.match(app, /auditRefsForFragments/);
  assert.match(app, /Co-visible context/);
  assert.match(app, /social lineage/);
  assert.match(app, /archiveContinuityRows\(archive\)/);
  assert.match(app, /audit-cache-line/);
  assert.match(app, /fragment bodies hidden/);
  assert.match(app, /omittedByReason/);
  assert.match(app, /roomModeSubtitle/);
  assert.match(app, /agentRuntimeMode/);
  assert.match(app, /runtime \$\{room\.agentRuntimeMode\}/);
  assert.match(app, /providerBoundarySummary/);
  assert.match(app, /"boundaries"\} visible/);
  assert.match(app, /agentModeBoundary/);
  assert.match(app, /latestProviderBoundaryForAgent/);
  assert.match(app, /agentProviderBoundaryMarkup/);
  assert.match(app, /requestProviderBoundaryRepair/);
  assert.match(app, /providerBoundaryRepairPrompt/);
  assert.match(app, /requestMemoryClaimReview/);
  assert.match(app, /memoryClaimReviewPrompt/);
  assert.match(app, /requestOpenQuestionReview/);
  assert.match(app, /openQuestionReviewPrompt/);
  assert.match(app, /requestPersonaDeltaReview/);
  assert.match(app, /personaDeltaReviewPrompt/);
  assert.match(app, /Latest provider boundary record/);
  assert.match(app, /Add provider boundary context ref/);
  assert.match(app, /Ask repair for provider boundary/);
  assert.match(app, /data-provider-boundary-repair-ref/);
  assert.match(app, /不是 agent 的沉默、失败人格或职责分配/);
  assert.match(app, /Ask review for memory claim/);
  assert.match(app, /data-memory-claim-review-ref/);
  assert.match(app, /memorySourceRefButtonMarkup/);
  assert.match(app, /data-memory-source-ref/);
  assert.match(app, /可质疑的房间沉淀，不是真理/);
  assert.match(app, /Ask review for open question/);
  assert.match(app, /Ask room to revisit open question/);
  assert.match(app, /data-open-question-review-ref/);
  assert.match(app, /未解决的房间问题，不是任务指派/);
  assert.match(app, /responseCount/);
  assert.match(app, /refinedCount/);
  assert.match(app, /deferredCount/);
  assert.match(app, /contestedCount/);
  assert.match(app, /Last response:/);
  assert.match(app, /refinedFromQuestionRef/);
  assert.match(app, /Refinement lineage:/);
  assert.match(app, /Ask review for persona delta/);
  assert.match(app, /Ask room to review persona delta/);
  assert.match(app, /请审阅这条 identity proposal/);
  assert.match(app, /data-persona-delta-review-ref/);
  assert.match(app, /可质疑的人格演化沉淀，不是固定职位或系统分配/);
  assert.match(app, /provider-backed cognition is available/);
  assert.match(app, /provider readiness does not imply live participation/);
  assert.match(app, /not agent silence or personality/);
  assert.match(app, /renderSocialState/);
  assert.match(app, /settingsReturnFocus/);
  assert.match(app, /setBackgroundInert/);
  assert.match(app, /trapSettingsFocus/);
  assert.match(app, /settingsFocusableElements/);
  assert.match(app, /toggleAttribute\("inert"/);
  assert.match(app, /selectedByType/);
  assert.match(app, /renderAuditFragments/);
  assert.match(app, /auditBoundaryNote/);
  assert.match(app, /evolutionLog/);
  assert.match(app, /roleClaims/);
  assert.match(app, /dailyMoodRecord/);
  assert.match(app, /archiveContinuityMarkup/);
  assert.match(app, /agentContinuityCount/);
  assert.match(app, /roleClaimCount/);
  assert.match(app, /dailyMoodCount/);
  assert.match(app, /dailyMoods/);
  assert.match(app, /Archive agent continuity sediment/);
  assert.match(app, /archiveContinuityRows/);
  assert.match(app, /archiveContinuityEvidenceRefs/);
  assert.match(app, /archiveContinuityEvidenceLabel/);
  assert.match(app, /archiveContinuityRefButtonsMarkup/);
  assert.match(app, /data-continuity-evidence-ref/);
  assert.match(app, /accepted continuity evidence refs/);
  assert.match(app, /agentDailyMoodMarkup/);
  assert.match(app, /currentDailyMoodForAgent/);
  assert.match(app, /Daily mood is reversible continuity/);
  assert.match(app, /agentRoleClaimsMarkup/);
  assert.match(app, /agentContinuityRefButtonsMarkup/);
  assert.match(app, /daily mood evidence refs/);
  assert.match(app, /personaContinuityEvidenceRefs/);
  assert.match(app, /dailyMoodRecord\?\.evidenceRefs/);
  assert.match(app, /dailyMoodRecord\?\.responseRefs/);
  assert.match(app, /claim\.responseRefs/);
  assert.match(app, /socialEvidenceRefsMarkup/);
  assert.match(app, /data-agent-continuity-ref/);
  assert.match(app, /findPersonaRoleClaim/);
  assert.match(app, /findPersonaDailyMoodByEvidenceRef/);
  assert.match(app, /findPersonaDelta/);
  assert.match(app, /personaEvolutionItems/);
  assert.match(app, /完整 evolution log/);
  assert.match(app, /kind: "delta"/);
  assert.match(app, /personaReviewRef: item\.deltaId/);
  assert.match(app, /seed posture only; not a fixed job/);
  assert.match(app, /contextRefs:\s*\[delta\.deltaId\]/);
  assert.match(app, /workspaces/);
  assert.match(app, /No private workspaces yet/);
  assert.match(app, /workspaceArtifactReviews/);
  assert.match(app, /requestWorkspaceArtifactReview/);
  assert.match(app, /workspaceArtifactReviewsForWorkspace/);
  assert.match(app, /workspaceArtifactReviewRef: artifactRefs\[0\]/);
  assert.match(app, /data-workspace-artifact-review-ref/);
  assert.match(app, /普通讨论不能复制私有内容/);
  assert.match(app, /skillCapsules/);
  assert.match(app, /No skill capsules yet/);
  assert.match(app, /skillCapsuleReviews/);
  assert.match(app, /requestSkillCapsuleReview/);
  assert.match(app, /skillCapsuleReviewsFor/);
  assert.match(app, /skillCapsuleReviewRef: skill\.capsuleId/);
  assert.match(app, /lineageRefs/);
  assert.match(app, /data-skill-capsule-review-ref/);
  assert.match(app, /普通讨论不能注册新 skill/);
  assert.match(app, /capabilityReviews/);
  assert.match(app, /capabilityHintList/);
  assert.match(app, /capabilityHintItems/);
  assert.match(app, /capabilityReviewsFor/);
  assert.match(app, /requestCapabilityReview/);
  assert.match(app, /capabilityReviewRef: hint\.capabilityRef/);
  assert.match(app, /pressureLineageRefs/);
  assert.match(app, /data-capability-review-ref/);
  assert.match(app, /普通讨论不能改变 wake score/);
  assert.match(app, /not authority, responsibility, trust proof/);
  assert.match(app, /socialLineageMarkup/);
  assert.match(app, /lineageRefButtonMarkup/);
  assert.match(app, /Pressure lineage:/);
  assert.match(app, /sideEffects/);
  assert.match(app, /No action requests yet/);
  assert.match(app, /memoryPressureBoundaries/);
  assert.match(app, /No memory pressure yet/);
  assert.match(app, /accepted, still provisional/);
  assert.match(app, /proposed, not adopted/);
  assert.match(app, /provisional sediment/);
  assert.match(app, /not truth/);
  assert.match(app, /openQuestions/);
  assert.match(app, /No open questions yet/);
  assert.match(app, /ref: question\.questionId/);
  assert.match(app, /questionReviewRef: question\.questionId/);
  assert.match(app, /type: "open question"/);
  assert.match(app, /unresolved room question/);
  assert.match(app, /question-context/);
  assert.match(app, /not a task assignment, consensus claim, or demand/);
  assert.match(app, /ref: boundary\.boundaryId/);
  assert.match(app, /topicProposals/);
  assert.match(app, /topicProposalReviews/);
  assert.match(app, /No topic proposals yet/);
  assert.match(app, /proposal\.responseCount/);
  assert.match(app, /topicProposalReviewsFor/);
  assert.match(app, /topicProposalReviewRef: proposal\.proposalId/);
  assert.match(app, /Ask review for topic proposal/);
  assert.match(app, /请重访这条话题建议/);
  assert.match(app, /会话秩序提案，不是隐藏路由/);
  assert.match(app, /mixedReviewPressures/);
  assert.match(app, /unresolved room pressure/);
  assert.match(app, /pressure-context/);
  assert.match(app, /data-mixed-pressure-review-ref/);
  assert.match(app, /requestMixedPressureReview/);
  assert.match(app, /请重访这条未解压力/);
  assert.match(app, /这只是房间压力索引，不是结论、任务或工作流/);
  assert.match(app, /proposal, not transfer/);
  assert.match(app, /rejectable proposal/);
  assert.match(app, /not control transfer/);
  assert.match(app, /Handoff response chain/);
  assert.match(app, /handoffResponseDetail/);
  assert.match(app, /请重访这条 handoff proposal/);
  assert.match(app, /invitations/);
  assert.match(app, /invitationReviews/);
  assert.match(app, /invitationReviewsFor/);
  assert.match(app, /Ask review for invitation/);
  assert.match(app, /请重访这次 social knock/);
  assert.match(app, /No invitations yet/);
  assert.match(app, /ref: invitation\.invitationId/);
  assert.match(app, /type: "invitation"/);
  assert.match(app, /social knock/);
  assert.match(app, /invitation-context/);
  assert.match(app, /not a speaking command, task assignment, or control flow/);
  assert.match(app, /silences/);
  assert.match(app, /No deliberate silences yet/);
  assert.match(app, /ref: silence\.silenceId/);
  assert.match(app, /pressureBoundaries/);
  assert.match(app, /No pressure boundaries yet/);
  assert.match(app, /ref: boundary\.boundaryId/);
  assert.match(app, /providerBoundaries/);
  assert.match(app, /No provider boundaries yet/);
  assert.match(app, /provider boundary 是运行时可见边界/);
  assert.match(app, /renderProviderBoundaryList/);
  assert.match(app, /provider-boundary-card/);
  assert.match(app, /providerBoundaryRoomBody/);
  assert.match(app, /providerBoundaryDiagnosticLabel/);
  assert.match(app, /recorded as bounded evidence/);
  assert.doesNotMatch(app, /<p class="social-body">\$\{escapeHtml\(boundary\.diagnostic/);
  assert.match(app, /provider-boundary-warning/);
  assert.match(app, /not agent silence · not personality/);
  assert.match(app, /providerBoundaryRepeatCount/);
  assert.match(app, /providerBoundaryFilter/);
  assert.match(app, /data-provider-boundary-filter/);
  assert.match(app, /providerBoundaryIsStale/);
  assert.match(app, /stale runtime record/);
  assert.match(app, /retired runtime pressure/);
  assert.match(app, /retiredBy/);
  assert.match(app, /retirementReason/);
  assert.match(app, /hidden stale/);
  assert.match(app, /provider-context/);
  assert.match(app, /pressureBoundaryCount/);
  assert.match(app, /providerBoundaryCount/);
  assert.match(app, /openQuestionTraceCount/);
  assert.match(app, /memoryChangeCount/);
  assert.match(app, /topicProposalCount/);
  assert.match(app, /handoffCount/);
  assert.match(app, /protocolCount/);
  assert.match(app, /proposal, not guidance/);
  assert.match(app, /temporary etiquette/);
  assert.match(app, /not command flow/);
  assert.match(app, /请重访这条临时房间礼仪/);
  assert.match(app, /silenceCount/);
  assert.match(app, /contestedCount/);
  assert.match(app, /not consensus/);
  assert.match(app, /compressed room time/);
  assert.match(app, /archive_is_compression_not_consensus/);
  assert.match(app, /archiveReviews/);
  assert.match(app, /review_request/);
  assert.match(app, /daily archive 会打开审阅节律/);
  assert.match(app, /selectedCount/);
  assert.match(app, /omittedCount/);
  assert.match(app, /largestFragment/);
  assert.match(app, /isNearBottom/);
  assert.match(app, /forceScrollOnNextRender/);
  assert.match(app, /newMessageJump\.hidden = true;/);
  assert.match(app, /mode: "seed"/);
  assert.doesNotMatch(app, /pageSize/);
  assert.doesNotMatch(app, /visibleMessages/);
  assert.match(app, /isLongMessage/);
  assert.match(app, /messageInput\.addEventListener\("keydown"/);
  assert.match(app, /内部服务未连接/);
  assert.match(css, /\.agent-list/);
  assert.match(css, /\.message-list/);
  assert.match(css, /\.topic small/);
  assert.match(css, /\.topic\.active small/);
  assert.match(css, /\.topic \.topic-revival/);
  assert.match(css, /\.topic \.topic-question/);
  assert.match(css, /\.living-overview/);
  assert.match(css, /\.living-overview\.expanded/);
  assert.match(css, /\.overview-toggle/);
  assert.match(css, /\.overview-toggle-summary/);
  assert.match(css, /\.overview-panel/);
  assert.match(css, /\.overview-panel\[hidden\]/);
  assert.match(css, /\.evidence-strip/);
  assert.match(css, /\.evidence-pill\.visible/);
  assert.match(css, /\.evidence-pill\.missing/);
  assert.match(css, /\.rhythm-evidence/);
  assert.match(css, /\.room-rhythm-choice-row/);
  assert.match(css, /\.room-rhythm-choice\.selected/);
  assert.match(css, /\.room-rhythm-choice\.missing-evidence/);
  assert.match(css, /\.room-rhythm-choice-label/);
  assert.match(css, /\.room-rhythm-choice-evidence/);
  assert.match(css, /\.room-rhythm-ref-row/);
  assert.match(css, /\.long-rhythm-ref-row/);
  assert.match(css, /\.scheduler-ref-row/);
  assert.match(css, /\.context-chip\.rhythm-context/);
  assert.match(css, /\.scheduler-evidence/);
  assert.match(css, /\.evidence-ref-row/);
  assert.match(css, /\.overview-tile/);
  assert.match(css, /\.memory-hygiene-summary/);
  assert.match(css, /\.memory-hygiene-fact/);
  assert.match(css, /\.continuity-sediment-summary/);
  assert.match(css, /\.continuity-sediment-fact/);
  assert.match(css, /\.archive-rhythm-summary/);
  assert.match(css, /\.archive-rhythm-fact/);
  assert.match(css, /\.provider-overview-pressure/);
  assert.match(css, /\.provider-overview-fact/);
  assert.match(css, /\.long-run-domain-row/);
  assert.match(css, /\.long-run-readiness-state\.stale/);
  assert.match(css, /\.long-run-domain\.ok/);
  assert.match(css, /\.long-run-domain\.gap/);
  assert.match(css, /\.long-run-action-boundary/);
  assert.match(css, /\.long-run-silence-reentry/);
  assert.match(css, /\.long-run-archive-rhythm/);
  assert.match(css, /\.long-run-memory-contest/);
  assert.match(css, /\.long-run-agent-continuity/);
  assert.match(css, /\.long-run-readiness-refs/);
  assert.match(css, /\.rhythm-balance-evidence/);
  assert.match(css, /\.rhythm-balance-pill\.balanced/);
  assert.match(css, /\.rhythm-balance-pill\.dominated/);
  assert.match(css, /\.rhythm-balance-ref-row/);
  assert.match(css, /\.timeline-preview/);
  assert.match(css, /\.timeline-row/);
  assert.match(css, /\.timeline-evidence-summary/);
  assert.match(css, /\.timeline-evidence-fact/);
  assert.match(css, /\.timeline-kind\.memory_contest/);
  assert.match(css, /\.timeline-kind\.agent_continuity/);
  assert.match(css, /\.timeline-kind\.provider_boundary/);
  assert.match(css, /\.audit-co-visible/);
  assert.match(css, /\.audit-domain-grid/);
  assert.match(css, /\.audit-domain\.visible/);
  assert.match(css, /\.overview-ref-button/);
  assert.match(css, /\.archive-continuity-refs/);
  assert.match(css, /\.mention-popover/);
  assert.match(css, /\.mention-option/);
  assert.match(css, /\.mention-option\.active/);
  assert.match(css, /\.mention-chip/);
  assert.match(css, /\.context-tray/);
  assert.match(css, /\.context-chip/);
  assert.match(css, /\.context-chip\.topic-context/);
  assert.match(css, /\.context-chip-label/);
  assert.match(css, /\.context-chip-ref/);
  assert.match(css, /\.message-row\.context-selected/);
  assert.doesNotMatch(css, /\.agent-avatar-image/);
  assert.match(css, /\.avatar-fallback/);
  assert.match(css, /\.social-actions/);
  assert.match(css, /\.social-context-button/);
  assert.match(css, /\.message-mentions/);
  assert.match(css, /\.message-context-refs/);
  assert.match(css, /height: 100dvh/);
  assert.match(css, /--safe-top: env\(safe-area-inset-top, 0px\)/);
  assert.match(css, /padding: var\(--safe-top\) var\(--safe-right\) var\(--safe-bottom\) var\(--safe-left\)/);
  assert.match(css, /\.settings-overlay[\s\S]*inset: var\(--safe-top\) var\(--safe-right\) var\(--safe-bottom\) var\(--safe-left\)/);
  assert.match(css, /\.settings-panel[\s\S]*var\(--safe-right\)[\s\S]*var\(--safe-bottom\)/);
  assert.match(css, /\.chat-shell[\s\S]*min-height: 0/);
  assert.match(css, /h1[\s\S]*text-overflow: ellipsis/);
  assert.match(css, /\.room-title[\s\S]*overflow: hidden/);
  assert.match(css, /\.live-pill[\s\S]*text-overflow: ellipsis/);
  assert.match(css, /@media \(max-width: 480px\)/);
  assert.match(css, /#composerState[\s\S]*display: none/);
  assert.match(css, /\.message-text\.scrollable/);
  assert.match(css, /\.message-row\.pending/);
  assert.match(css, /\.message-row\.actions-open/);
  assert.match(css, /\.message-action-trigger/);
  assert.match(css, /\.message-context-marker/);
  assert.match(css, /\.message-overflow-menu/);
  assert.match(css, /\.message-actions[\s\S]*z-index: 4/);
  assert.match(css, /\.message-overflow-menu[\s\S]*z-index: 5/);
  assert.match(css, /\.social-approve-button/);
  assert.match(css, /\.social-execute-button/);
  assert.match(css, /\.composer\.draft-mode textarea/);
  assert.match(css, /\.composer\.expanded textarea/);
  assert.match(css, /\.composer-tools button\[aria-pressed="true"\]/);
  assert.doesNotMatch(css, /\.message-pager/);
  assert.match(css, /\.empty-state/);
  assert.match(css, /#3370ff/);
  assert.match(css, /\.settings-panel\.open/);
  assert.match(css, /\.new-message-jump/);
  assert.match(css, /\.agent-mode-boundary/);
  assert.match(css, /\.agent-daily-mood/);
  assert.match(css, /\.agent-role-claims/);
  assert.match(css, /\.agent-continuity-ref-button/);
  assert.match(css, /\.agent-provider-boundary/);
  assert.match(css, /\.agent-provider-boundary\.active/);
  assert.match(css, /\.provider-boundary-controls/);
  assert.match(css, /\.provider-boundary-card\.stale/);
  assert.match(css, /\.provider-boundary-filter button\.active/);
  assert.match(css, /\.agent-state-pills/);
  assert.match(css, /\.social-repair-button/);
  assert.match(css, /\.social-retire-button/);
  assert.match(css, /\.social-review-button/);
  assert.match(css, /\.pressure-review-button/);
  assert.match(css, /\.context-chip\.pressure-context/);
  assert.match(css, /\.context-chip\.question-context/);
  assert.match(css, /\.context-chip\.invitation-context/);
  assert.match(css, /\.context-chip\.archive-review-context/);
  assert.match(css, /\.context-chip\.continuity-context/);
  assert.match(css, /\.badge\.degraded/);
  assert.match(css, /\.mode-pill/);
  assert.match(css, /\.audit-card/);
  assert.match(css, /\.audit-facts/);
  assert.match(css, /\.audit-cache-line/);
  assert.match(css, /\.audit-fragment-group/);
  assert.match(css, /\.audit-chip/);
  assert.match(css, /\.handoff-card/);
  assert.match(css, /\.handoff-boundary/);
  assert.match(css, /\.handoff-responses/);
  assert.match(css, /\.handoff-response/);
  assert.match(css, /\.handoff-facts/);
  assert.match(css, /\.memory-card/);
  assert.match(css, /\.memory-state-boundary/);
  assert.match(css, /\.memory-facts/);
  assert.match(css, /\.memory-source-refs/);
  assert.match(css, /\.protocol-card/);
  assert.match(css, /\.protocol-boundary/);
  assert.match(css, /\.protocol-facts/);
  assert.match(css, /\.archive-card/);
  assert.match(css, /\.archive-boundary/);
  assert.match(css, /\.archive-continuity/);
  assert.match(css, /\.archive-continuity-row/);
  assert.match(css, /\.archive-stats/);
  assert.match(css, /\.fragment-list/);
  assert.match(css, /\.fragment-row/);
  assert.match(css, /\.fragment-lineage/);
  assert.match(css, /\.social-lineage/);
  assert.match(css, /\.social-evidence-refs/);
  assert.match(css, /\.audit-boundary/);
  assert.match(css, /\.section-title/);
  assert.match(css, /\.section-actions/);
  assert.match(css, /\.section-hint/);
  assert.match(css, /\.archive-review-list/);
  assert.match(css, /\.secondary-button/);
  assert.match(css, /\.muted-card/);

  const serialized = `${html}\n${app}\n${css}`;
  assert.doesNotMatch(serialized, /sk-[A-Za-z0-9]{12,}/);
  assert.doesNotMatch(serialized, /tp-[A-Za-z0-9]{12,}/);
});
